### ISSUE TITLE
right clickign milk into a spout gives strange buggy results

### ISSUE THREAD

**Issue by Yarden-zamir** [Yarden-zamir/Create-Prepare-to-Dye#383]

**Comment by Yarden-zamir** [comment]
![](https://cdn.discordapp.com/attachments/1169568140850626655/1183424579646009354/image.png?ex=65884906&is=6575d406&hm=9695ba61a7abed311d7c564bdbfe6adef65eef5ebbc4a9c8a38bf70d1f362b3f&)

**Comment by alexytomi** [comment]
When right clicking a milk bucket into a spout it start a client desync bug where you seem to be holding an empty bucket yet the bucket can still be used to place milk while the spout says it is filled with milk whilst not actually being filled with milk as revealed by a relog.

The bug is purely cosmetic

**Comment by Yarden-zamir** [comment]
Very odd, wonder what's causing it

**Comment by Yarden-zamir** [comment]
Fixed
