### ISSUE TITLE
Dye stuffs

### ISSUE THREAD

**Issue by Yarden-zamir** [Yarden-zamir/Create-Prepare-to-Dye#72]

**Comment by PandaBoy444** [comment]
Advantages:
- gives more opportunity for cool recipes
> - drop stuff in water dye to make other stuff
> - dye stuff in the coolest way
Disadvantages:
- 16 more stuff to clutter the game
- might not have enough recipes to justify itseld

**Comment by PandaBoy444** [comment]
What if fluid dye were actually just other fluids that can also dye. Example honey can dye things yellow, lava can dye things orange (funny coz you need to be carful)
Maybe water makes blue? that would be weird
Chocolate = brown

**Comment by PandaBoy444** [comment]
What if water colored stuff based on the biome you are in?

**Comment by PandaBoy444** [comment]
@tulkinRB had an idea for dying stuff that isn't cloth-like with a more viscous version of the dye using slime
examples

- combining slime and dye in mixer and applying the result to the input dyeable item
- applying slime and then applying liquid dye on the dyeable item

**Comment by PandaBoy444** [comment]
We can also just drop the dye and the dyeable in water instead of having a liquid version of dyes. Then if we go with tulkin's idea we can throw slime + dye + dyeable. That is actually something we can also do programmatically: we can go through all recipes that have dye in ingredients and only one other ingredient, then remove them and replace with fluid one.

**Comment by PandaBoy444** [comment]
problem: leather armor dyeing recipe is dynamic, ie it doesn't actually exist until you craft, it's this so that you can dye with complex colors. Need to find a way around this or just allow it in this case
